global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "demo_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "scooter-rental-rest:8080"
          - "notification-service:8083"
          - "audit-service:8082"
          - "analytics-service:9090"